substitutions:
  project_ver_let: u
  default_button_config: "Toggle on Release"


packages:
  kauf_plug_base: !include kauf-plug.yaml


dashboard_import:
  package_import_url: github://KaufHA/PLF10/kauf-plug.yaml


esphome:
  name_add_mac_suffix: true


# re-adding wifi component to get forced hash
wifi:

  # add forced hash in update bin file which isn't needed for dashboard import.
  # Allows saving wifi credentials across update.
  forced_hash: 1432266978


